export class PayoutReviewDataGridDto {
	public payoutDetail_Id: number;
	public payout_Id: number;
	public applApac: string;
	public dsaCrn: string;
	public dsaName: string;
	public dsaType: string;
	public customerName: string;
	public location: string;
	public payoutMonth: string;
	public disbursalMonth: string;
	public productCode: string;
	public profile: string;
	public caseType: string;
	public portfolio: string;
	public schemeDescription: string;
	public isFraud: string;
	public chequeStatus: string;
	public sanctionAmount: number;
	public disbursalAmount: number;
	public processingFeeCollectedWithoutGst: number;
	public processingFeeCollectedPercentages: number;
	public netPayPercentages: number;
	public netPayToCustomer: number;
	public kliPremiumWithoutGst: number;
	public kliPayoutPercentages: number;
	public kliPayoutAmount: number;
	public kgiPremiumWithoutGst: number;
	public kgiPayoutPercentages: number;
	public kgiPayoutAmount: number;
	public gstPayoutPercentages: number;
	public gstAmount: number;
	public totalPayoutWithGst: number;
	public payoutAmount: number;
	public finalPayout: number;
	public quarterlyPayout: number;
	public clawbackAmount: number;
	public dealIRR: number;
	public kgiPremium: number;
	public kliPremium: number;
	public payoutPercentages: number;
	public processingFeeToBeCollected: number;
	public processingFeeCollectedWithGst: number;
	public odPayoutPercentages: number;
	public cutOffAmount: number;
	public processingFeeToBeCollectedPercentages: number;
	public deductionReason: string;
	public cancelApplApac: string;
	public cancelMainPartyId: string;
	public cancelPartyName: string;
	public cancelDisbursalDate: Date;
	public cancellationDate: Date;
	public cancelDisbursalAmount: number;
	public cancelPayoutMonth: Date;
	public cancelPayoutAmount: number;
	public deductionMonth: Date;
	public deductedAmount: number;
	public remarkMap: Map<string, string>;
	public isSpecial: string;
	public isChecked:boolean;
	public otcPending:string;
	public pddPending:string;
	public chequeUnrealized:string
	public isDirty: string;
	constructor() { }
}
